id: ee4ba36355334bbf867e8e9a9d384418
initial_creation_type: ocr
source_metadata:
  volumes:
    ecf9f2ab87174c218047d5c8f7308ab1:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: སྒྲོན་མ་གསལ་བར་བྱེད་པ་ཞེས་བྱ་བའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1453
      volume_number: 15
